services:
  # Servidor principal (main.py - puerto 8000)
  - type: web
    name: semaforo-bot-main
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m playwright install chromium && chmod +x start_main.sh"
    startCommand: "./start_main.sh"
    envVars:
      # IMPORTANTE: Redis debe configurarse manualmente en Render Dashboard
      # Opción 1: Crear Redis desde Dashboard y pegar REDIS_URL aquí
      # Opción 2: Usar Redis externo (Upstash gratis: https://upstash.com)
      # Opción 3: Dejar en blanco y el bot usará memoria local (se pierde al reiniciar)
      - key: REDIS_HOST
        value: "localhost"
      - key: REDIS_PORT
        value: "6379"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: EXCHANGE_NAME
        value: binance
      - key: DEBUG
        value: "False"
    healthCheckPath: /status

  # Servidor SSE Long/Short (api_longshort_ondemand.py - puerto 8001)
  - type: web
    name: semaforo-bot-longshort
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && python -m playwright install chromium && chmod +x start_longshort.sh"
    startCommand: "./start_longshort.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
    healthCheckPath: /status

  # Frontend estático (index_pro.html)
  - type: web
    name: semaforo-bot-frontend
    runtime: static
    buildCommand: ""
    staticPublishPath: ./static
    routes:
      - type: rewrite
        source: /*
        destination: /index_pro.html
